version: "2.0"
language: en
pipeline:
  - name: "WhitespaceTokenizer"
  - name: "CountVectorsFeaturizer"
  - name: "EmbeddingIntentClassifier"
policies:
  - name: "MemoizationPolicy"
  - name: "TEDPolicy"
